version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: clinic_chatbot_db
    environment:
      POSTGRES_DB: clinic_chatbot
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_dev_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot_user -d clinic_chatbot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
